build_task: pipelines/gradle/tasks/gradle-assemble.yml # don't change
deploy_dev_task: pipelines/cf/tasks/blue-green-deploy.yml # don't change

app_name: eureka
jar_name: bberg-eureka

github_app_repo_uri: https://github.com/Valiken/bberg.eureka.git
github_app_repo_branch: master # don't change

github_pipelines_repo_uri: https://github.com/Valiken/training-pipelines-initial.git
github_pipelines_repo_branch: master # don't change

version_bucket: rscale-training-bucket # don't change
version_bucket_region_name: us-west-2 # don't change

version_key: bberg-eureka-version
initial_version: 0.0.1

artifact_regexp: bberg-eureka-(.*).jar # set to 'bberg-eureka-(.*).jar'.  ex: sgreenberg-eureka-(.*).jar
artifact_bucket: rscale-training-bucket # don't change
artifact_bucket_region_name: us-west-2 # don't change

cf_dev_api: api.run.pivotal.io
cf_dev_organization: rscale-training-1
cf_dev_space: brian.berg@cgi.com
cf_dev_hostname: eureka-bberg
cf_dev_domain: cfapps.io
cf_dev_manifest: eureka_dev.yml
