---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/cf-cli

inputs:
- name: pipelines
- name: app
- name: version

outputs:
- name:

run:
  path: pipelines/integration/tasks/integration.sh
